name: Update Readme

on:
  push:
  schedule:
    - cron: 0 */12 * * *

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate README.md
        uses: actions-js/profile-readme@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: DiscordAnaxes

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coauthor_email: DiscordAnaxes@users.noreply.github.com
          coauthor_name: DiscordAnaxes
